# .github/workflows/git-sync.yml

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  git-sync:
    if: ${{ github.repository == 'zetsux/mindspace-ml-be' }}
    runs-on: ubuntu-latest
    steps:
      - name: git-sync
        uses: wei/git-sync@v3
        with:
          source_repo: "https://robbypambudi:${{secrets.ACCESS_TOKEN}}@github.com/zetsux/mindspace-ml-be.git"
          source_branch: "main"
          destination_repo: "https://robbypambudi:${{secrets.ACCESS_TOKEN}}@github.com/MindsSpace/mindspace-ml.git"
          destination_branch: "main"
